version: "3"
services:
  ssh-server:
    container_name: ssh-server
    build: ./ssh-server
    ports:
      - 22:22
    volumes:
      - data:/data
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
volumes:
  data:
