FROM lscr.io/linuxserver/openssh-server:latest

COPY sshd_config /etc/ssh



#BEFORE BUILD THE CONTAINER CREATE SSH KEY
#ssh-keygen -b 4096 -f id_rsa_for_sshu1

#INSPECT
#sudo docker logs --tail 50 --follow --timestamps ssh-server